export * from './department'
export * from './types/department.types'
export * from './employee'
export * from './types/employee.types'
export * from './designation'
export * from './types/designation.types'
export * from './types/employee-document.types'
